### ISSUE TITLE
Урок 1: Основы HTML и CSS

### ISSUE THREAD

**Issue by maryiv** [daryau/Front-End-Test#1]
- [x] увеличить размер второй и третей иконки (примерно как на скрине ниже), чтобы было больше похоже на иконки в задании; знаю, что их там нельзя было вырезать, но просто чтобы выглядели похоже (сейчас первая самая крупная)
![image](https://user-images.githubusercontent.com/11769636/68627807-68c63c80-04e7-11ea-940f-f38a7581d58b.png)
- [x] добавить класс для активной страницы
![image](https://user-images.githubusercontent.com/11769636/68627927-bb9ff400-04e7-11ea-9ca1-caca6b5dfb61.png)
- [x] не замечание, поскольку у нас не было мобильного дизайна и тут полный полёт фантазии - главное, чтобы не сыпалось; но желательно для небольших разрешений по возможности сохранять структуру (например, текст, выделенный фоном по логике является цитатой сообщения, о котором пришла нотификация, и лучше располагать в том де столбце); и второй момент картинки на мобильном и планшете становятся больше даже чем на десктопе изначально
![image](https://user-images.githubusercontent.com/11769636/68628286-cdce6200-04e8-11ea-9930-589bd647890b.png)

### Полезная инфа
Шрифты:

- https://www.w3schools.com/cssref/css_websafe_fonts.asp (раздел Sans-Serif Fonts)
- https://css-tricks.com/snippets/css/better-helvetica/
- https://css-tricks.com/snippets/css/using-font-face/

Спасибо за работу 👍

**Comment by daryau** [comment]
Готово ☺️
